import Footer from "@/components/Landing/Footer";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main lang="en">
        <div className="min-h-screen">{children}</div>
      </main>
      <Footer />
    </>
  );
}
