import Footer from "@/components/Landing/Footer";
import "../globals.css";
import { CartProvider } from "@/components/Subscription/Cart/CartProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main lang="en">
        <CartProvider>
          <div className="min-h-screen">{children}</div>
        </CartProvider>
      </main>
      <Footer />
    </>
  );
}
